os: Visual Studio 2015
environment:

  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
 
install:
  # Go To libnanomsg Destination Directory
  - cd ..
  # Download And Compile libnanomsg
  - ps: Start-FileDownload 'https://github.com/nanomsg/nanomsg/archive/1.1.4.zip'
  - 7z x 1.1.4.zip
  - cd nanomsg-1.1.4
  - mkdir build
  - cd build
  - cmake -G"Visual Studio 14 Win64" -DNN_ENABLE_DOC=OFF ..
  - cmake --build .
  - cmake --build . --target install
  # Return To nanomsg-rs Git Directory
  - cd ../../nanomsg-rs
  # Download And Install Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV


build_script:
  - set LIB=%LIB%;C:\Program Files\nanomsg\lib
  - set PATH=%PATH%;C:\Program Files\nanomsg\bin
  - cargo build
 
test_script:
  - set LIB=%LIB%;C:\Program Files\nanomsg\lib
  - set PATH=%PATH%;C:\Program Files\nanomsg\bin
  - cargo test
  # Move libnanomsg To Test nanomsg_sys
  - mv ..\nanomsg-1.1.4 .\nanomsg-1.1.4 && cd nanomsg_sys
  - cargo test
